# Generated by Django 4.2.3 on 2023-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_court', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
