# Generated by Django 4.2.3 on 2023-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_court', '0002_alter_court_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='latitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='court',
            name='longitude',
            field=models.CharField(max_length=200),
        ),
    ]
