# Generated by Django 4.2.3 on 2023-07-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
