# Generated by Django 4.2.3 on 2023-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_user', '0004_alter_user_city_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
