# Generated by Django 4.2.3 on 2023-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_court', '0001_initial'),
        ('modules_user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='modules_court.court'),
        ),
    ]
